In [1]:
import pandas as pd
import numpy as np
import re, pickle, gzip, os

def convert_sample_names(x):
    x = re.sub(r'^noncanonical_', '', x)
    x = re.sub(r'^canonical_', '', x)
    x = re.sub(r'_fdp$', '', x)
    return x

In [2]:
cutoffs_canon_trembl = pd.read_csv(
    './IonbotData_ionbot_ranks_300925/results/peptide_level/all_bysample_stats.csv',
    usecols=['sample','subset','dataset','database','search_type','approach',"Max rank 1% paired FDP"]
    )
cutoffs_canon_trembl = cutoffs_canon_trembl[cutoffs_canon_trembl.database!='open'].copy()
cutoffs_canon_trembl['sample'] = cutoffs_canon_trembl['sample'].apply(convert_sample_names)
cutoffs_canon_trembl['subset'] = 'Canonical'
cutoffs_canon_trembl.fillna(-1, inplace=True)
cutoffs_canon_trembl.sort_values('Max rank 1% paired FDP')

,Max rank 1% paired FDP,sample,subset,dataset,database,search_type,approach
10,1453.0,130327_o2_05_hu_C3_2hr,Canonical,PXD002057,trembl,ClosedSearch,classic
2,1574.0,130327_o2_03_hu_C2_2hr,Canonical,PXD002057,canon,ClosedSearch,classic
4,1613.0,130327_o2_05_hu_C3_2hr,Canonical,PXD002057,canon,ClosedSearch,classic
8,1622.0,130327_o2_03_hu_C2_2hr,Canonical,PXD002057,trembl,ClosedSearch,classic
6,2029.0,130327_o2_01_hu_C1_2hr,Canonical,PXD002057,trembl,ClosedSearch,classic
...,...,...,...,...,...,...,...
91,19944.0,Sample-MCF,Canonical,PXD014258,canon,OpenSearch,classic
18,20564.0,Sample-BT474,Canonical,PXD014258,canon,ClosedSearch,classic
90,20694.0,Sample-BT474,Canonical,PXD014258,canon,OpenSearch,classic
21,20707.0,Sample-BT474,Canonical,PXD014258,trembl,ClosedSearch,classic
93,21017.0,Sample-BT474,Canonical,PXD014258,trembl,OpenSearch,classic

In [3]:
cutoffs_openprot = pd.read_csv(
    './IonbotData_ionbot_ranks_300925/results/all_bysample_stats_subsets.csv',
    usecols=['sample','subset','dataset','database','search_type','approach',"Max rank 1% paired FDP"]
    )
cutoffs_openprot['sample'] = cutoffs_openprot['sample'].apply(convert_sample_names)
cutoffs_openprot.database = cutoffs_openprot.database.map({'open':'openprot'})
cutoffs_openprot.subset = cutoffs_openprot.subset.map({'noncanonical':'NonCanonical', 'canonical':'Canonical'})
cutoffs_openprot.sort_values('Max rank 1% paired FDP')

,Max rank 1% paired FDP,sample,subset,dataset,database,search_type,approach
7,14.0,130327_o2_02_hu_P1_2hr,NonCanonical,PXD002057,openprot,ClosedSearch,classic
11,15.0,130327_o2_06_hu_P3_2hr,NonCanonical,PXD002057,openprot,ClosedSearch,classic
43,15.0,AM17,NonCanonical,PXD005833,openprot,ClosedSearch,classic
45,15.0,AM19,NonCanonical,PXD005833,openprot,ClosedSearch,classic
44,16.0,AM18,NonCanonical,PXD005833,openprot,ClosedSearch,classic
...,...,...,...,...,...,...,...
36,NaN,AM10,NonCanonical,PXD005833,openprot,ClosedSearch,classic
37,NaN,AM11,NonCanonical,PXD005833,openprot,ClosedSearch,classic
39,NaN,AM13,NonCanonical,PXD005833,openprot,ClosedSearch,classic
56,NaN,130327_o2_03_hu_C2_2hr,NonCanonical,PXD002057,openprot,OpenSearch,classic
86,NaN,AM12,NonCanonical,PXD005833,openprot,OpenSearch,classic

In [4]:
cutoffs = pd.concat([cutoffs_canon_trembl,cutoffs_openprot], ignore_index=True)
cutoffs.fillna(-1, inplace=True)
cutoffs['sample2'] = cutoffs.apply(
    lambda row: row['sample']+'-closed' if row['search_type']=='ClosedSearch' else row['sample'],
    axis=1
)
cutoffs[['subset','dataset','database','search_type']].value_counts(sort=False)

subset        dataset    database  search_type
Canonical     PXD002057  canon     ClosedSearch     6
                                   OpenSearch       6
                         openprot  ClosedSearch     6
                                   OpenSearch       6
                         trembl    ClosedSearch     6
                                   OpenSearch       6
              PXD005833  canon     ClosedSearch    15
                                   OpenSearch      15
                         openprot  ClosedSearch    15
                                   OpenSearch      15
                         trembl    ClosedSearch    15
                                   OpenSearch      15
              PXD014258  canon     ClosedSearch     3
                                   OpenSearch       3
                         openprot  ClosedSearch     3
                                   OpenSearch       3
                         trembl    ClosedSearch     3
                                   OpenSearch       3
NonCanonical  PXD002057  openprot  ClosedSearch     6
                                   OpenSearch       6
              PXD005833  openprot  ClosedSearch    15
                                   OpenSearch      15
              PXD014258  openprot  ClosedSearch     3
                                   OpenSearch       3
Name: count, dtype: int64

In [5]:
cutoffs2 = cutoffs.set_index(['sample2','subset','database']).to_dict()['Max rank 1% paired FDP']
cutoffs2

{('130327_o2_01_hu_C1_2hr-closed', 'Canonical', 'canon'): 2123.0,
 ('130327_o2_02_hu_P1_2hr-closed', 'Canonical', 'canon'): 4659.0,
 ('130327_o2_03_hu_C2_2hr-closed', 'Canonical', 'canon'): 1574.0,
 ('130327_o2_04_hu_P2_2hr-closed', 'Canonical', 'canon'): 3799.0,
 ('130327_o2_05_hu_C3_2hr-closed', 'Canonical', 'canon'): 1613.0,
 ('130327_o2_06_hu_P3_2hr-closed', 'Canonical', 'canon'): 3994.0,
 ('130327_o2_01_hu_C1_2hr-closed', 'Canonical', 'trembl'): 2029.0,
 ('130327_o2_02_hu_P1_2hr-closed', 'Canonical', 'trembl'): 4620.0,
 ('130327_o2_03_hu_C2_2hr-closed', 'Canonical', 'trembl'): 1622.0,
 ('130327_o2_04_hu_P2_2hr-closed', 'Canonical', 'trembl'): 3815.0,
 ('130327_o2_05_hu_C3_2hr-closed', 'Canonical', 'trembl'): 1453.0,
 ('130327_o2_06_hu_P3_2hr-closed', 'Canonical', 'trembl'): 3890.0,
 ('Sample-BT474-closed', 'Canonical', 'canon'): 20564.0,
 ('Sample-MCF-closed', 'Canonical', 'canon'): 18829.0,
 ('SampleHela-closed', 'Canonical', 'canon'): 16214.0,
 ('Sample-BT474-closed', 'Canonical', 'trembl'): 20707.0,
 ('Sample-MCF-closed', 'Canonical', 'trembl'): 18872.0,
 ('SampleHela-closed', 'Canonical', 'trembl'): 16255.0,
 ('AM7-closed', 'Canonical', 'canon'): 4247.0,
 ('AM8-closed', 'Canonical', 'canon'): 4086.0,
 ('AM9-closed', 'Canonical', 'canon'): 5733.0,
 ('AM10-closed', 'Canonical', 'canon'): 4928.0,
 ('AM11-closed', 'Canonical', 'canon'): 5304.0,
 ('AM12-closed', 'Canonical', 'canon'): 5637.0,
 ('AM13-closed', 'Canonical', 'canon'): 5864.0,
 ('AM14-closed', 'Canonical', 'canon'): 5805.0,
 ('AM15-closed', 'Canonical', 'canon'): 5095.0,
 ('AM16-closed', 'Canonical', 'canon'): 6639.0,
 ('AM17-closed', 'Canonical', 'canon'): 3966.0,
 ('AM18-closed', 'Canonical', 'canon'): 4118.0,
 ('AM19-closed', 'Canonical', 'canon'): 5639.0,
 ('AM20-closed', 'Canonical', 'canon'): 4847.0,
 ('AM21-closed', 'Canonical', 'canon'): 4334.0,
 ('AM7-closed', 'Canonical', 'trembl'): 4488.0,
 ('AM8-closed', 'Canonical', 'trembl'): 4157.0,
 ('AM9-closed', 'Canonical', 'trembl'): 5829.0,
 ('AM10-closed', 'Canonical', 'trembl'): 5055.0,
 ('AM11-closed', 'Canonical', 'trembl'): 5379.0,
 ('AM12-closed', 'Canonical', 'trembl'): 5678.0,
 ('AM13-closed', 'Canonical', 'trembl'): 5799.0,
 ('AM14-closed', 'Canonical', 'trembl'): 5849.0,
 ('AM15-closed', 'Canonical', 'trembl'): 5191.0,
 ('AM16-closed', 'Canonical', 'trembl'): 6683.0,
 ('AM17-closed', 'Canonical', 'trembl'): 4231.0,
 ('AM18-closed', 'Canonical', 'trembl'): 4385.0,
 ('AM19-closed', 'Canonical', 'trembl'): 5885.0,
 ('AM20-closed', 'Canonical', 'trembl'): 4882.0,
 ('AM21-closed', 'Canonical', 'trembl'): 4425.0,
 ('130327_o2_01_hu_C1_2hr', 'Canonical', 'canon'): 3118.0,
 ('130327_o2_02_hu_P1_2hr', 'Canonical', 'canon'): 6238.0,
 ('130327_o2_03_hu_C2_2hr', 'Canonical', 'canon'): 2353.0,
 ('130327_o2_04_hu_P2_2hr', 'Canonical', 'canon'): 5327.0,
 ('130327_o2_05_hu_C3_2hr', 'Canonical', 'canon'): 2505.0,
 ('130327_o2_06_hu_P3_2hr', 'Canonical', 'canon'): 5680.0,
 ('130327_o2_01_hu_C1_2hr', 'Canonical', 'trembl'): 3204.0,
 ('130327_o2_02_hu_P1_2hr', 'Canonical', 'trembl'): 6114.0,
 ('130327_o2_03_hu_C2_2hr', 'Canonical', 'trembl'): 2324.0,
 ('130327_o2_04_hu_P2_2hr', 'Canonical', 'trembl'): 5377.0,
 ('130327_o2_05_hu_C3_2hr', 'Canonical', 'trembl'): 2592.0,
 ('130327_o2_06_hu_P3_2hr', 'Canonical', 'trembl'): 5526.0,
 ('Sample-BT474', 'Canonical', 'canon'): 20694.0,
 ('Sample-MCF', 'Canonical', 'canon'): 19944.0,
 ('SampleHela', 'Canonical', 'canon'): 16738.0,
 ('Sample-BT474', 'Canonical', 'trembl'): 21017.0,
 ('Sample-MCF', 'Canonical', 'trembl'): 19731.0,
 ('SampleHela', 'Canonical', 'trembl'): 16051.0,
 ('AM7', 'Canonical', 'canon'): 5133.0,
 ('AM8', 'Canonical', 'canon'): 5444.0,
 ('AM9', 'Canonical', 'canon'): 7233.0,
 ('AM10', 'Canonical', 'canon'): 6354.0,
 ('AM11', 'Canonical', 'canon'): 6763.0,
 ('AM12', 'Canonical', 'canon'): 7329.0,
 ('AM13', 'Canonical', 'canon'): 7469.0,
 ('AM14', 'Canonical', 'canon'): 7507.0,
 ('AM15', 'Canonical', 'canon'): 6357.0,
 ('AM16', 'Canonical', 'canon'): 8384.0,
 ('AM17', 'Canonical', 'canon'): 5245.0,
 ('AM18', 'Canonical', 'canon'): 5536.0,
 ('AM19', 'Canonical', 'canon'): 7133.0,
 ('AM20', 'Canonical', 'canon'): 5828.0,
 ('AM21', 'Canonical', 'canon'): 5265.0,
 ('AM7', 'Canonical', 'trembl'): 5237.0,
 ('AM8', 'Canonical', 'trembl'): 5437.0,
 ('AM9', 'Canonical', 'trembl'): 7302.0,
 ('AM10', 'Canonical', 'trembl'): 6340.0,
 ('AM11', 'Canonical', 'trembl'): 6727.0,
 ('AM12', 'Canonical', 'trembl'): 7242.0,
 ('AM13', 'Canonical', 'trembl'): 7271.0,
 ('AM14', 'Canonical', 'trembl'): 7534.0,
 ('AM15', 'Canonical', 'trembl'): 6439.0,
 ('AM16', 'Canonical', 'trembl'): 8470.0,
 ('AM17', 'Canonical', 'trembl'): 5266.0,
 ('AM18', 'Canonical', 'trembl'): 5587.0,
 ('AM19', 'Canonical', 'trembl'): 7257.0,
 ('AM20', 'Canonical', 'trembl'): 5866.0,
 ('AM21', 'Canonical', 'trembl'): 5299.0,
 ('130327_o2_01_hu_C1_2hr-closed', 'Canonical', 'openprot'): 2069.0,
 ('130327_o2_02_hu_P1_2hr-closed', 'Canonical', 'openprot'): 4575.0,
 ('130327_o2_03_hu_C2_2hr-closed', 'Canonical', 'openprot'): 1540.0,
 ('130327_o2_04_hu_P2_2hr-closed', 'Canonical', 'openprot'): 3761.0,
 ('130327_o2_05_hu_C3_2hr-closed', 'Canonical', 'openprot'): 1643.0,
 ('130327_o2_06_hu_P3_2hr-closed', 'Canonical', 'openprot'): 3986.0,
 ('130327_o2_01_hu_C1_2hr-closed', 'NonCanonical', 'openprot'): 24.0,
 ('130327_o2_02_hu_P1_2hr-closed', 'NonCanonical', 'openprot'): 14.0,
 ('130327_o2_03_hu_C2_2hr-closed', 'NonCanonical', 'openprot'): 18.0,
 ('130327_o2_04_hu_P2_2hr-closed', 'NonCanonical', 'openprot'): -1.0,
 ('130327_o2_05_hu_C3_2hr-closed', 'NonCanonical', 'openprot'): 23.0,
 ('130327_o2_06_hu_P3_2hr-closed', 'NonCanonical', 'openprot'): 15.0,
 ('Sample-BT474-closed', 'Canonical', 'openprot'): 20767.0,
 ('Sample-MCF-closed', 'Canonical', 'openprot'): 18991.0,
 ('SampleHela-closed', 'Canonical', 'openprot'): 16332.0,
 ('Sample-BT474-closed', 'NonCanonical', 'openprot'): -1.0,
 ('Sample-MCF-closed', 'NonCanonical', 'openprot'): 60.0,
 ('SampleHela-closed', 'NonCanonical', 'openprot'): 42.0,
 ('AM7-closed', 'Canonical', 'openprot'): 4478.0,
 ('AM8-closed', 'Canonical', 'openprot'): 3977.0,
 ('AM9-closed', 'Canonical', 'openprot'): 5874.0,
 ('AM10-closed', 'Canonical', 'openprot'): 5038.0,
 ('AM11-closed', 'Canonical', 'openprot'): 5483.0,
 ('AM12-closed', 'Canonical', 'openprot'): 5807.0,
 ('AM13-closed', 'Canonical', 'openprot'): 5767.0,
 ('AM14-closed', 'Canonical', 'openprot'): 5845.0,
 ('AM15-closed', 'Canonical', 'openprot'): 5184.0,
 ('AM16-closed', 'Canonical', 'openprot'): 6617.0,
 ('AM17-closed', 'Canonical', 'openprot'): 4256.0,
 ('AM18-closed', 'Canonical', 'openprot'): 4334.0,
 ('AM19-closed', 'Canonical', 'openprot'): 5759.0,
 ('AM20-closed', 'Canonical', 'openprot'): 4923.0,
 ('AM21-closed', 'Canonical', 'openprot'): 4393.0,
 ('AM7-closed', 'NonCanonical', 'openprot'): 18.0,
 ('AM8-closed', 'NonCanonical', 'openprot'): -1.0,
 ('AM9-closed', 'NonCanonical', 'openprot'): -1.0,
 ('AM10-closed', 'NonCanonical', 'openprot'): -1.0,
 ('AM11-closed', 'NonCanonical', 'openprot'): -1.0,
 ('AM12-closed', 'NonCanonical', 'openprot'): 17.0,
 ('AM13-closed', 'NonCanonical', 'openprot'): -1.0,
 ('AM14-closed', 'NonCanonical', 'openprot'): 18.0,
 ('AM15-closed', 'NonCanonical', 'openprot'): 18.0,
 ('AM16-closed', 'NonCanonical', 'openprot'): 17.0,
 ('AM17-closed', 'NonCanonical', 'openprot'): 15.0,
 ('AM18-closed', 'NonCanonical', 'openprot'): 16.0,
 ('AM19-closed', 'NonCanonical', 'openprot'): 15.0,
 ('AM20-closed', 'NonCanonical', 'openprot'): 29.0,
 ('AM21-closed', 'NonCanonical', 'openprot'): 27.0,
 ('130327_o2_01_hu_C1_2hr', 'Canonical', 'openprot'): 3119.0,
 ('130327_o2_02_hu_P1_2hr', 'Canonical', 'openprot'): 6085.0,
 ('130327_o2_03_hu_C2_2hr', 'Canonical', 'openprot'): 2433.0,
 ('130327_o2_04_hu_P2_2hr', 'Canonical', 'openprot'): 5311.0,
 ('130327_o2_05_hu_C3_2hr', 'Canonical', 'openprot'): 2427.0,
 ('130327_o2_06_hu_P3_2hr', 'Canonical', 'openprot'): 5546.0,
 ('130327_o2_01_hu_C1_2hr', 'NonCanonical', 'openprot'): 102.0,
 ('130327_o2_02_hu_P1_2hr', 'NonCanonical', 'openprot'): 73.0,
 ('130327_o2_03_hu_C2_2hr', 'NonCanonical', 'openprot'): -1.0,
 ('130327_o2_04_hu_P2_2hr', 'NonCanonical', 'openprot'): 65.0,
 ('130327_o2_05_hu_C3_2hr', 'NonCanonical', 'openprot'): 71.0,
 ('130327_o2_06_hu_P3_2hr', 'NonCanonical', 'openprot'): 79.0,
 ('Sample-BT474', 'Canonical', 'openprot'): 20246.0,
 ('Sample-MCF', 'Canonical', 'openprot'): 19702.0,
 ('SampleHela', 'Canonical', 'openprot'): 16584.0,
 ('Sample-BT474', 'NonCanonical', 'openprot'): 81.0,
 ('Sample-MCF', 'NonCanonical', 'openprot'): 146.0,
 ('SampleHela', 'NonCanonical', 'openprot'): 53.0,
 ('AM7', 'Canonical', 'openprot'): 5147.0,
 ('AM8', 'Canonical', 'openprot'): 5309.0,
 ('AM9', 'Canonical', 'openprot'): 7195.0,
 ('AM10', 'Canonical', 'openprot'): 6343.0,
 ('AM11', 'Canonical', 'openprot'): 6800.0,
 ('AM12', 'Canonical', 'openprot'): 7242.0,
 ('AM13', 'Canonical', 'openprot'): 7290.0,
 ('AM14', 'Canonical', 'openprot'): 7500.0,
 ('AM15', 'Canonical', 'openprot'): 6428.0,
 ('AM16', 'Canonical', 'openprot'): 8260.0,
 ('AM17', 'Canonical', 'openprot'): 5302.0,
 ('AM18', 'Canonical', 'openprot'): 5556.0,
 ('AM19', 'Canonical', 'openprot'): 7267.0,
 ('AM20', 'Canonical', 'openprot'): 5967.0,
 ('AM21', 'Canonical', 'openprot'): 5201.0,
 ('AM7', 'NonCanonical', 'openprot'): 53.0,
 ('AM8', 'NonCanonical', 'openprot'): 43.0,
 ('AM9', 'NonCanonical', 'openprot'): 62.0,
 ('AM10', 'NonCanonical', 'openprot'): 58.0,
 ('AM11', 'NonCanonical', 'openprot'): 71.0,
 ('AM12', 'NonCanonical', 'openprot'): -1.0,
 ('AM13', 'NonCanonical', 'openprot'): 63.0,
 ('AM14', 'NonCanonical', 'openprot'): 96.0,
 ('AM15', 'NonCanonical', 'openprot'): 42.0,
 ('AM16', 'NonCanonical', 'openprot'): 97.0,
 ('AM17', 'NonCanonical', 'openprot'): 63.0,
 ('AM18', 'NonCanonical', 'openprot'): 70.0,
 ('AM19', 'NonCanonical', 'openprot'): 101.0,
 ('AM20', 'NonCanonical', 'openprot'): 50.0,
 ('AM21', 'NonCanonical', 'openprot'): 33.0}

In [6]:
with gzip.open('custom-rank-cutoffs.gz','wb') as outfile:
    pickle.dump(cutoffs2, outfile)

In [7]:
# to read the pickle
with gzip.open('custom-rank-cutoffs.gz','rb') as infile:
    b = pickle.load(infile)

In [8]:
cutoffs2 == b

True